/** vite.config.ts
 * @author Dibyasmita
 * @date 18-1-2026
 * @description This file has the vite configurations and was auto-generated by vite.
 * @returns Vite Configurations
 */


// Imports
import path from "path";
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';


// Configurations
export default defineConfig({
  // Plugins Used
  plugins: [
    react(),
    tailwindcss(),
  ],
  
  // Resolve Symbols
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});