/** utils.tsx
 * @author Shadcn UI
 * @date 18-1-2026
 * @description This file was auto - generated by Shadcn UI. (Try not to make changes)
 * @returns Utility Functions
 */
 
 
 // Imports
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";


// Exports
export function cn(...inputs: ClassValue[]) {
  
  // Return
  return twMerge(
    clsx(inputs)
  );
};
